server:
  port: 8080
spring:
  datasource:
    initilization-mode: always
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      springframework: ERROR